### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by JosePineiro** [AyrA/QuickTorrent#1]
I download the exe file and not work.
Do not download any with hash A7055D06E5A8F7F816EC01AC7F7F5243D3CB008F (your first example hash)

Need open the port 54321 in router?

**Comment by AyrA** [comment]
Opening a port is not needed but it would help.

The hash you try is very old already. Try a newer hash: `30987C19CF0EAE3CF47766F387C621FA78A58AB9`

This application is only for people who don't download torrents frequently. It can take up to 5 minutes before torrents start downloading.

**Comment by JosePineiro** [comment]
thanks
